language: node_js
node_js:
  - 'node'

notifications:
  email: false

cache:
  yarn: true

before_cache:
  - rm -rf ./node_modules/.cache

before_install:
  - export TZ="Asia/Shanghai"
  - date

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install --frozen-lockfile

script:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  fqdn: announcement.owmod.net
  local_dir: $TRAVIS_BUILD_DIR/dist
  on:
    branch: master

env:
  global:
    - secure: OCCR+7PRKT/vaQHQ8qcpPa0cWbLVTpFqNA/G7/15cqaR1FikFvytz0jk8xwZn09sKgYTmqC7DSObONDUITgr/eLQa1g+pAZU4VEVw8AZuRNL/wh/LYzPK8ciWLXKg179hFep/QNvnWr9EFGRHRWLqaMwUvqIhPD5KdmL2IlayTMOknENib6j3JLMLtzZs4ntBZi9fsaIbUO0sRjaU8zQEYHTDHLnep9sF3IkDHbQzk80l7U7heiNwx8J5XpAX0NAT2KTCx/4Zx9QXGYwxk/Ccbn1AQ1v8TlyVgFG4+WYn5LJ0kYPZcNDZ+jT1wxu6q8Y4yISSTV1xiIM9KzyPa9+7/blA/vdtBPm7DhmeXHos9CrCD5N3OYgTGpgxvN+33ectw59GlbBFlSVhBKg9oiilSoFjF1+hys50169HbHspbpS6MtqPoy2+PWLeBVmXEFjlf+mOkUJH0Wt5G6PUEwQ4TAFBJCTjaz1npky4P5YMuHzVkWkFY8P7+SroHVpr01CduWejy44+XV+EHu/lJlsq2s6NW5jllOxuvzIC4QLtWKXq4cQ7kX01Ei69AFt1jRXtI1LUPrdOhK0dPEXJtu9rrOfEQ191gR7sQ+iSDwl8E+LhzsxSJDlgKu4jmC9jai1GT2SmfSRQ+1c83I0oPCACi5NR+Guu68KkFG8/KUF2yo=
